name: trim_talk
description: "Transcribes voice messages automatically, making conversations clear and efficient."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.5+30

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  permission_handler: ^12.0.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  intl: any
  just_audio: ^0.10.4
  path: ^1.8.3
  path_provider: ^2.1.2
  url_launcher: ^6.2.6
  # workmanager:
  #   git:
  #     url: https://github.com/fluttercommunity/flutter_workmanager.git
  #     ref: b783000
  go_router: ^16.0.0
  awesome_extensions: ^2.0.16
  disable_battery_optimization:
    git:
      url: https://github.com/pvsvamsi/Disable-Battery-Optimizations
      ref: 3bd744d03c416859bbaedecd61c1c11fc022ed75

  optimization_battery:
    git:
      url: https://github.com/tempo-riz/optimization_battery.git
      ref: 5921eceba2b32d7117c21bbcafc6ed264e0efb6b
  country_flags: ^3.2.0
  audio_waveforms: ^1.0.5
  flutter_native_splash: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.1.1
  feedback_github:
    git:
      url: https://github.com/tempo-riz/feedback_github.git
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent.git
      ref: 2cea396
  device_info_plus: ^11.2.1
  flutter_slidable: ^4.0.0
  flutter_scrolling_fab_animated: ^0.1.5
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  loading_animation_widget: ^1.2.1
  firebase_crashlytics: ^4.0.4
  firebase_analytics: ^11.2.1
  pigeon: ^22.3.0
  groq_sdk:
    git:
      url: https://github.com/tempo-riz/groq-dart-sdk.git
  week_of_year: ^2.2.0
  in_app_update: ^4.2.3
  upgrader: ^11.3.1
  mime: ^2.0.0
  # https://github.com/arthenica/ffmpeg-kit/wiki/Packages
  # ffmpeg_kit_flutter_full_gpl: ^6.0.3
  ogg_opus_player:
    git:
      url: https://github.com/tempo-riz/flutter-plugins-pr
      path: packages/ogg_opus_player
      ref: 3a6e62178864a5c0028d85c3fef52505d6839b90
  in_app_review: ^2.0.9
  share_plus: ^11.0.0
  package_info_plus: ^8.0.2
  flutter_reaction_button:
    git:
      url: https://github.com/tempo-riz/flutter-reaction-button.git
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  notification_listener_service: ^0.3.4
  collection: ^1.18.0
  deepl_dart: ^2.0.0
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.4.3
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/audio/

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_1024.png"
  background_color_ios: "#ffffff"
  remove_alpha_ios: true

flutter_native_splash:
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#ffffff"
  image: assets/images/splash.png

  # From Android 12 onwards, the splash screen is handled differently than in previous versions.
  # Please visit https://developer.android.com/guide/topics/ui/splash-screen
  # Following are specific parameters for Android 12+.
  # android_12:
  #   # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  #   # the app's launcher icon will be used instead.
  #   # Please note that the splash screen will be clipped to a circle on the center of the screen.
  #   # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  #   # 640 pixels in diameter.
  #   # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  #   # 768 pixels in diameter.
  #   image: assets/images/splash.png

  #   # Splash screen background color.
  #   color: "#ffffff"

  #   # App icon background color.
  #   #icon_background_color: "#111111"

  #   # The branding property allows you to specify an image used as branding in the splash screen.
  #   #branding: assets/dart.png

  #   # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
  #   # apply when the device is in dark mode. If they are not specified, the app will use the
  #   # parameters from above.
  #   #image_dark: assets/android12splash-invert.png
  #   #color_dark: "#042a49"
  #   #icon_background_color_dark: "#eeeeee"
