# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    # increment_build_number(xcodeproj: "Runner.xcodeproj")
    # increment_version_number(
    #   bump_type: "patch", # Automatically increment patch version number
    #   xcodeproj: "Runner.xcodeproj"
    #   )
    # build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store(
      ipa: "../build/ios/ipa/TrimTalk.ipa",
      force: true,# Skip verification of HTML preview file
      precheck_include_in_app_purchases: true,
      skip_metadata: false,
      skip_screenshots: true,
      submit_for_review: true, 
      automatic_release: true, # Automatically release the app once the review is approved
      reject_if_possible: true, # Reject the binary if it is in review and a new build is uploaded

        # Use of Advertising Identifier (IDFA) is required to submit
      submission_information: { # options : https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_submission.rb
        add_id_info_uses_idfa: false #,
        # add_id_info_serves_ads: false,
        # add_id_info_tracks_install: true,
        # add_id_info_tracks_action: true,
        # add_id_info_limits_tracking: true
        # content_rights_has_rights: true,
        # content_rights_contains_third_party_content: true,
        # export_compliance_platform: 'ios',
        # export_compliance_compliance_required: false,
        # export_compliance_encryption_updated: false,
        # export_compliance_app_type: nil,
        # export_compliance_uses_encryption: false,
        # export_compliance_is_exempt: false,
        # export_compliance_contains_third_party_cryptography: false,
        # export_compliance_contains_proprietary_cryptography: false,
        # export_compliance_available_on_french_store: false
      }
    )
  end
end
